areas_index:
    path:     /
    defaults: { _controller: "CpdgUsuarioBundle:Areas:index" }
    methods:  GET

areas_show:
    path:     /{id}/show
    defaults: { _controller: "CpdgUsuarioBundle:Areas:show" }
    methods:  GET

areas_new:
    path:     /new
    defaults: { _controller: "CpdgUsuarioBundle:Areas:new" }
    methods:  [GET, POST]

areas_edit:
    path:     /{id}/edit
    defaults: { _controller: "CpdgUsuarioBundle:Areas:edit" }
    methods:  [GET, POST]

areas_delete:
    path:     /{id}/delete
    defaults: { _controller: "CpdgUsuarioBundle:Areas:delete" }
    methods:  DELETE
